### ISSUE TITLE
请问客户端用Clash怎么配置，用Trojan的模板好像不行

### ISSUE THREAD

**Issue by sephiroth945** [cty123/TrojanRust#7]
服务端运行起来了，客户端用Clash，按之前Trojan的模板测试不行，配置如下
- name: "Trojan-RS"
  type: trojan
  server: *.*.*.*
  port: 443
  password: "****"
  sni: "www.***.com"
  skip-cert-verify: true

PS，服务端的配置sample少了个 mode参数，我配置成
“mode”: "TCP"
其它参照模板配置，不知道有没有影响

**Comment by cty123** [comment]
啊对，mode其实就是transport，如果是单纯基于tcp+tls传输的trojan协议，那么mode这里填TCP

**Comment by cty123** [comment]
Example 里面的是对的 https://github.com/cty123/TrojanRust/tree/main/example，可以参考下

**Comment by cty123** [comment]
有客户端和服务端的配置文件吗？日志有吗？看看什么问题

**Comment by cty123** [comment]
我自己的clash配置 + example/tcp_trojan/server.json 

```yml
- name: "trojan"
  type: trojan
  server: 10.0.0.7
  port: 8081
  password: 123123
  sni: example.com
  skip-cert-verify: true
```
